# Generated by Django 3.0.5 on 2020-04-21 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='offering',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Offering'),
        ),
    ]
